/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_ffmpeglib_FFmpegKit */

#ifndef _Included_com_demo_ffmpeglib_FFmpegKit
#define _Included_com_demo_ffmpeglib_FFmpegKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_ffmpeglib_FFmpegKit
 * Method:    getFFmpegName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_demo_ffmpeglib_FFmpegKit_getFFmpegName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
